
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programaleftPLUSMINUSleftTIMESDIVIDErightPOWERrightUMINUSATRIBUIR_KW DERIVAR_KW DIVIDE EQUALS E_KW ID INTEGRAR_KW LPAREN MINUS MOSTRAR_KW NUMBER PLUS POWER RPAREN TIMES\nprograma : atribuir_stmt\n         | atribuir_stmt E_KW mostrar_stmt\n\natribuir_stmt : ATRIBUIR_KW ID EQUALS exp\n\nmostrar_stmt : MOSTRAR_KW ID\n\nexp : exp PLUS exp\n    | exp MINUS exp\n    | exp TIMES exp\n    | exp DIVIDE exp\n    | exp POWER exp\n\nexp : LPAREN exp RPAREN\n\nexp : MINUS exp %prec UMINUS\n\nexp : NUMBER\n\nexp : ID\n\nexp : DERIVAR_KW exp\n\nexp : INTEGRAR_KW exp\n'
    
_lr_action_items = {'ATRIBUIR_KW':([0,],[3,]),'$end':([1,2,6,9,10,11,14,22,24,25,26,27,28,29,30,31,],[0,-1,-2,-4,-13,-3,-12,-11,-14,-15,-5,-6,-7,-8,-9,-10,]),'E_KW':([2,10,11,14,22,24,25,26,27,28,29,30,31,],[4,-13,-3,-12,-11,-14,-15,-5,-6,-7,-8,-9,-10,]),'ID':([3,7,8,12,13,15,16,17,18,19,20,21,],[5,9,10,10,10,10,10,10,10,10,10,10,]),'MOSTRAR_KW':([4,],[7,]),'EQUALS':([5,],[8,]),'LPAREN':([8,12,13,15,16,17,18,19,20,21,],[13,13,13,13,13,13,13,13,13,13,]),'MINUS':([8,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[12,-13,18,12,12,-12,12,12,12,12,12,12,12,-11,18,18,18,-5,-6,-7,-8,-9,-10,]),'NUMBER':([8,12,13,15,16,17,18,19,20,21,],[14,14,14,14,14,14,14,14,14,14,]),'DERIVAR_KW':([8,12,13,15,16,17,18,19,20,21,],[15,15,15,15,15,15,15,15,15,15,]),'INTEGRAR_KW':([8,12,13,15,16,17,18,19,20,21,],[16,16,16,16,16,16,16,16,16,16,]),'PLUS':([10,11,14,22,23,24,25,26,27,28,29,30,31,],[-13,17,-12,-11,17,17,17,-5,-6,-7,-8,-9,-10,]),'TIMES':([10,11,14,22,23,24,25,26,27,28,29,30,31,],[-13,19,-12,-11,19,19,19,19,19,-7,-8,-9,-10,]),'DIVIDE':([10,11,14,22,23,24,25,26,27,28,29,30,31,],[-13,20,-12,-11,20,20,20,20,20,-7,-8,-9,-10,]),'POWER':([10,11,14,22,23,24,25,26,27,28,29,30,31,],[-13,21,-12,-11,21,21,21,21,21,21,21,21,-10,]),'RPAREN':([10,14,22,23,24,25,26,27,28,29,30,31,],[-13,-12,-11,31,-14,-15,-5,-6,-7,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'atribuir_stmt':([0,],[2,]),'mostrar_stmt':([4,],[6,]),'exp':([8,12,13,15,16,17,18,19,20,21,],[11,22,23,24,25,26,27,28,29,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> atribuir_stmt','programa',1,'p_programa','main.py',63),
  ('programa -> atribuir_stmt E_KW mostrar_stmt','programa',3,'p_programa','main.py',64),
  ('atribuir_stmt -> ATRIBUIR_KW ID EQUALS exp','atribuir_stmt',4,'p_atribuir_stmt','main.py',73),
  ('mostrar_stmt -> MOSTRAR_KW ID','mostrar_stmt',2,'p_mostrar_stmt','main.py',79),
  ('exp -> exp PLUS exp','exp',3,'p_exp_binop','main.py',85),
  ('exp -> exp MINUS exp','exp',3,'p_exp_binop','main.py',86),
  ('exp -> exp TIMES exp','exp',3,'p_exp_binop','main.py',87),
  ('exp -> exp DIVIDE exp','exp',3,'p_exp_binop','main.py',88),
  ('exp -> exp POWER exp','exp',3,'p_exp_binop','main.py',89),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_group','main.py',95),
  ('exp -> MINUS exp','exp',2,'p_exp_unary_minus','main.py',101),
  ('exp -> NUMBER','exp',1,'p_exp_number','main.py',107),
  ('exp -> ID','exp',1,'p_exp_variable','main.py',113),
  ('exp -> DERIVAR_KW exp','exp',2,'p_exp_derivar','main.py',119),
  ('exp -> INTEGRAR_KW exp','exp',2,'p_exp_integrar','main.py',125),
]
